import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import NewsCard from "../../components/cards/NewsCard";
import Basic from "../../components/layouts/Basic";
import MainWrapper from "../../components/layouts/MainWrapper";
import News from "../../components/News";
import API from "../../services/API";

const Post = ({ news }) => {
    const router = useRouter();
    const { post } = router.query;
    return (
        <>
            <Head>
                <title className="capitalize">Stateflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Basic>
                <MainWrapper>
                <div className="flex flex-col space-y-3 md:w-2/3 lg:w-full mx-auto">
                    <NewsCard news={news} />
                </div>
                </MainWrapper>
            </Basic>
        </>
    );
};

export default Post;

export async function getServerSideProps(context) {
    try {
        const { post } = context.params;
        console.log(context.params);
        const id = post.split("-").pop();
        console.log(id);
        const news = (await API.get(`/posts/${id}`)).data.data;
        return {
            props: {
                news,
            },
        };
    } catch (error) {
        return {
            props: {
                error: error.message,
            },
        };
    }
}
