FROM node:16

# Create app directory
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .

# RUN yarn install
# If you are building your code for production
# RUN npm ci --only=production

EXPOSE 3000
CMD [ "yarn", "dev" ]