version: "3.9"
services:
    nginx:
        image: divyanshukaushik/stateflix-nginx:latest
        restart: always
        depends_on:
            - backend
        ports:
            - "80:80"
            - "443:443"
        # volumes:
        #     - ./nginx/certbot:/etc/letsencrypt
        #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        #     - ./nginx/conf.d:/etc/nginx/conf.d
    # certbot:
    #     image: certbot/certbot
    #     restart: always
    #     volumes:
    #         - ./nginx/certbot:/etc/letsencrypt
    #     command: certonly --webroot -w /etc/letsencrypt -d api.stateflix.com -d www.api.stateflix.com --email divyanshukaushik44@gmail.com
    # redis:
    #     container_name: redis_cache
    #     image: redis
    #     restart: always
    #     ports:
    #         - "6379:6379"
    #     command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    # frontend:
    #     image: divyanshukaushik/stateflix-frontend:latest
    #     env_file:
    #         - ./frontend/.env.local
    #     networks:
    #         - stateflix

    backend:
        image: divyanshukaushik/stateflix-backend:latest
        environment:
            - MONGO_URI=${MONGO_URI}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT_C=${REDIS_PORT_C}
            - REDIS_PASSWORD_C=${REDIS_PASSWORD_C}
            - REDIS_URL_C=${REDIS_URL_C}
            - REDIS_URL=${REDIS_URL}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
            - DK_AWS_ACCESS_KEY_ID=${DK_AWS_ACCESS_KEY_ID}
            - DK_AWS_SECRET_ACCESS_KEY=${DK_AWS_SECRET_ACCESS_KEY}
            - DK_AWS_REGION=${DK_AWS_REGION}
            - DK_AWS_S3_BUCKET_NAME=${DK_AWS_S3_BUCKET_NAME}
            - STATEFLIX_API_KEY=${STATEFLIX_API_KEY}
            - DK_GOOGLE_CLIENT_ID=${DK_GOOGLE_CLIENT_ID}
            - DK_GOOGLE_CLIENT_SECRET=${DK_GOOGLE_CLIENT_SECRET}
            - STATEFLIX_CLIENT_URI=${STATEFLIX_CLIENT_URI}


