version: "3.8"
services:
    nginx:
        build: ./nginx
        volumes:
            - ./nginx:/home
        restart: always
        depends_on:
            - api
        ports:
            - "80:80"
            - "443:443"
        networks:
            - stateflix
    redis:
        container_name: redis_cache
        image: redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes: 
            - ./redis_cache:/data
        env_file:
          - ./api/.env
        networks:
            - stateflix
    api:
        container_name: api
        build: 
            context: ./api
            dockerfile: Dockerfile.dev
        env_file:
          - ./api/.env
        ports:
            - "4000:4000"
        expose:
            - 4000
        volumes:
            - ./api:/app
        depends_on:
            - redis
        networks:
            - stateflix
networks:
    stateflix:
        driver: bridge