# version: "3"
# services:

#   admin:
#     build: 
#       context: ./admin
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     networks:
#       - mern-network
#     volumes:
#       - ./client/src:/usr/app/src
#       - ./client/public:/usr/app/public
#     depends_on:
#       - server
#     environment:
#       - REACT_APP_SERVER=http://localhost:5000
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start
#     stdin_open: true
#     tty: true

#   client:
#     build: 
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - 3001:3001
#     networks:
#       - mern-network
#     volumes:
#       - ./client/src:/usr/app/src
#       - ./client/public:/usr/app/public
#     depends_on:
#       - server
#     environment:
#       - REACT_APP_SERVER=http://localhost:5000
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start
#     stdin_open: true
#     tty: true
  
#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - 4000:4000
#     networks:
#       - mern-network
#     volumes:
#       - ./server/src:/usr/app/src
#     depends_on:
#       - db
#     environment:
#       - MONGO_URL=mongodb://db:27017
#       - CLIENT=http://localhost:3000
#     command: /usr/app/node_modules/.bin/nodemon -L src/index.js

#   db:
#     image: mongo:3.6.19-xenial
#     ports:
#       - 27017:27017
#     networks:
#       - mern-network
#     volumes:
#       - mongo-data:/data/db

# networks:
#   mern-network:
#     driver: bridge

# volumes:
#   mongo-data:
#     driver: local

version: "3.8"
services:
    nginx:
        image: divyanshukaushik/stateflix-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        image: divyanshukaushik/stateflix-frontend:latest
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        image: divyanshukaushik/stateflix-backend:latest
        environment:
            - FRONTEND_URI=${FRONTEND_URI}
            - SERVER_URI=${SERVER_URI}
            - PORT=${PORT}
            - DB_URI=${DB_URI}
            - COOKIE_NAME=${COOKIE_NAME}
            - COOKIE_SECRET=${COOKIE_SECRET}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
            - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
            - FACEBOOK_CALLBACK_ROUTE=${FACEBOOK_CALLBACK_ROUTE}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - GOOGLE_CALLBACK_ROUTE=${GOOGLE_CALLBACK_ROUTE}
