version: "3.9"
services:
    nginx:
        image: divyanshukaushik/stateflix-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"
        networks:
            - stateflix

    frontend:
        image: divyanshukaushik/stateflix-frontend:latest
        env_file:
            - ./frontend/.env.local
        networks:
            - stateflix

    backend:
        image: divyanshukaushik/stateflix-backend:latest
        env_file:
            - ./backend/.env
        networks:
            - stateflix
    
networks:
    stateflix:
        driver: bridge



