version: "3.9"
services:
    nginx:
        image: divyanshukaushik/stateflix-nginx:latest
        restart: always
        depends_on:
            # - frontend
            - backend
        ports:
            - "80:80"
    redis:
        container_name: redis_cache
        image: redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    # frontend:
    #     image: divyanshukaushik/stateflix-frontend:latest
    #     env_file:
    #         - ./frontend/.env.local
    #     networks:
    #         - stateflix

    backend:
        image: divyanshukaushik/stateflix-backend:latest
        env_file:
            - ./backend/.env


