version: "3.8"
services:
    nginx:
        # image: divyanshukaushik/stateflix-nginx:latest
        build: ./nginx
        volumes:
            - ./nginx:/home
        restart: always
        depends_on:
            # - frontend
            - backend
        ports:
            - "80:80"
        networks:
            - stateflix
    redis:
        container_name: redis_cache
        image: redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
            - ./redis_cache:/data
        networks:
            - stateflix


    # frontend:
    #     # image: divyanshukaushik/stateflix-frontend:latest
    #     build: 
    #         context: ./frontend 
    #         dockerfile: Dockerfile.dev
    #     env_file:
    #       - ./frontend/.env.local
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./frontend:/app
    #     networks:
    #         - stateflix

    backend:
        container_name: backend
        # image: divyanshukaushik/stateflix-backend:latest
        build: 
            context: ./backend
            dockerfile: Dockerfile.dev
        env_file:
          - ./backend/.env
        ports:
            - "4000:4000"
        expose:
            - 4000
        volumes:
            - ./backend:/app
        depends_on:
            - redis
        networks:
            - stateflix
networks:
    stateflix:
        driver: bridge