version: "3.8"
services:
    nginx:
        image: divyanshukaushik/stateflix-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        image: divyanshukaushik/stateflix-frontend:latest
        env_file:
          - ./frontend/.env.local

    backend:
        image: divyanshukaushik/stateflix-backend:latest
        env_file:
          - ./backend/.env