version: "3.8"
services:
    nginx:
        # image: divyanshukaushik/stateflix-nginx:latest
        build: ./nginx
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        # image: divyanshukaushik/stateflix-frontend:latest
        build: ./frontend
        env_file:
          - ./frontend/.env.local
        ports:
            - "3000:3000"
        networks:
            - stateflix

    backend:
        # image: divyanshukaushik/stateflix-backend:latest
        build: ./backend
        env_file:
          - ./backend/.env
        ports:
            - "4000:4000"
        networks:
            - stateflix
networks:
    stateflix:
        driver: bridge