import Head from "next/head";
import StoreProvider from "../app/StoreProvider";
import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Stateflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* global state wrapper (Context Api) */}
            <StoreProvider>
                <body className="flex flex-col min-h-screen">
                    {/* header section containing navbar  */}
                    <Header />
                    {/* all pages  */}
                    <div className="flex-grow">
                    <Component {...pageProps} />

                    </div>
                    {/* footer section  */}
                    <Footer />
                </body>
            </StoreProvider>
        </>
    );
}

export default MyApp;
