import Head from "next/head";
import Basic from "../components/layouts/Basic";
import News from "../components/News";
import API from "../services/API";
import MainWrapper from "../components/layouts/MainWrapper";

export default function Home({news,ads}) {
    return (
        <>
            <Head>
                <title>Stateflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
          <Basic>
          <MainWrapper ads={ads}>
              <News news={news} />
          </MainWrapper>
          </Basic>
        </>
    );
}

export async function getServerSideProps(context) {
  try {
    const news= (await API.get("/posts")).data.data;
    const ads = (await API.get("/ads")).data.data;
    return {
      props: {
        news,ads
      }
    }
    
  } catch (error) {
    console.log(error);
    return {
      props: {
        error: error.message,
      },
    }
  }
}
