import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import PublisherCard from "../../components/cards/PublisherCard";
import Basic from "../../components/layouts/Basic";
import MainWrapper from "../../components/layouts/MainWrapper";
import News from "../../components/News";
import API from "../../services/API";

const NewsByPublisher = ({ news, totalCount,publisher }) => {
    const router = useRouter();
    return (
        <>
            <Head>
                <title className="capitalize">Stateflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Basic>
                <MainWrapper>
                    {/* publisher detail  */}
                        <PublisherCard publisher={publisher} posts={totalCount} />

                    {/* news  */}
                    <News news={news} />
                </MainWrapper>
            </Basic>
        </>
    );
};

export default NewsByPublisher;

export async function getServerSideProps(context) {
    try {
        const { publisher } = context.params;
        console.log(publisher);
        const res = (await API.get(`/posts?publishers=${publisher}`)).data;
        const pub_data = (await API.get(`/publisher/${publisher}`)).data.data;
        return {
            props: {
                news: res.data,
                totalCount: res.totalCount,
                publisher:pub_data
            },
        };
    } catch (error) {
        return {
            props: {
                error: error.message,
            },
        };
    }
}
