import React from "react";
import Head from "next/head";
import Basic from "../../components/layouts/Basic";
import MainWrapper from "../../components/layouts/MainWrapper";
import API from "../../services/API";
import PublisherCard from "../../components/cards/PublisherCard";
import Link from "next/link";

const Publishers = ({ publishers }) => {
    return (
        <>
            <Head>
                <title className="capitalize">Stateflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Basic>
                <MainWrapper>
                    {/* all publishers  */}
                    <div className="flex flex-col items-center justify-center space-y-3">
                        {publishers?.map((publisher) => (
                            <Link key={publisher._id} href={`/publishers/${publisher.slug}`} className="w-full">
                                <PublisherCard
                                    publisher={publisher}
                                    posts={2}
                                />
                            </Link>
                        ))}
                    </div>
                </MainWrapper>
            </Basic>
        </>
    );
};

export default Publishers;

export async function getStaticProps(context) {
    try {
        const publishers = (await API.get("/publisher")).data.data;
        return {
            props: {
                publishers,
            },
        };
    } catch (error) {
        return {
            props: {
                error: error.message,
            },
        };
    }
}
